""" These are the templates for the big letters made out of slackmojis """

big_letter_templates =\
    {
        "a": (
            "----\n"
            "-XX-\n"
            "X--X\n"
            "X--X\n"
            "XXXX\n"
            "X--X\n"
            "X--X\n"
            "X--X\n"
            "----\n"
        ),
        "b": (
                "----\n"
                "XXX-\n"
                "X--X\n"
                "X--X\n"
                "XXXX\n"
                "X--X\n"
                "X--X\n"
                "XXX-\n"
                "----"
            ),
        "c": (
                "----\n"
                "-XXX\n"
                "X---\n"
                "X---\n"
                "X---\n"
                "X---\n"
                "X---\n"
                "-XXX\n"
                "----"
            ),
        "d": (
                "----\n"
                "XXX-\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "XXX-\n"
                "----"
            ),
        "e": (
                "----\n"
                "XXXX\n"
                "X---\n"
                "X---\n"
                "XXXX\n"
                "X---\n"
                "X---\n"
                "XXXX\n"
                "----"
            ),
        "f": (
                "----\n"
                "XXXX\n"
                "X---\n"
                "X---\n"
                "XXXX\n"
                "X---\n"
                "X---\n"
                "X---\n"
                "----"
            ),
        "g": (
                "----\n"
                "XXXX\n"
                "X---\n"
                "X---\n"
                "X-XX\n"
                "X--X\n"
                "X--X\n"
                "XXXX\n"
                "----"
            ),
        "h": (
                "----\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "XXXX\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "----"
            ),
        "i": (
                "---\n"
                "XXX\n"
                "-X-\n"
                "-X-\n"
                "-X-\n"
                "-X-\n"
                "-X-\n"
                "XXX\n"
                "---"
            ),
        "j": (
                "----\n"
                "XXXX\n"
                "---X\n"
                "---X\n"
                "---X\n"
                "X--X\n"
                "X--X\n"
                "-XX-\n"
                "----"
            ),
        "k": (
                "----\n"
                "X--X\n"
                "X--X\n"
                "X-X-\n"
                "XX--\n"
                "X-X-\n"
                "X--X\n"
                "X--X\n"
                "----"
            ),
        "l": (
                "----\n"
                "X---\n"
                "X---\n"
                "X---\n"
                "X---\n"
                "X---\n"
                "X---\n"
                "XXXX\n"
                "----"
            ),
        "m": (
                "-----\n"
                "X---X\n"
                "XX-XX\n"
                "XXXXX\n"
                "X-X-X\n"
                "X---X\n"
                "X---X\n"
                "X---X\n"
                "-----"
            ),
        "n": (
                "----\n"
                "X---X\n"
                "XX--X\n"
                "XX--X\n"
                "X-X-X\n"
                "X--XX\n"
                "X--XX\n"
                "X---X\n"
                "----"
            ),
        "o": (
                "----\n"
                "XXXX\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "XXXX\n"
                "----"
            ),
        "p": (
                "----\n"
                "XXX-\n"
                "X--X\n"
                "X--X\n"
                "XXX-\n"
                "X---\n"
                "X---\n"
                "X---\n"
                "----"
            ),
        "q": (
                "-----\n"
                "-XX--\n"
                "X--X-\n"
                "X--X-\n"
                "X--X-\n"
                "X-XX-\n"
                "X--X-\n"
                "-XX-X\n"
                "-----\n"
            ),
        "r": (
                "-----\n"
                "XXX--\n"
                "X--X-\n"
                "X--X-\n"
                "XXX--\n"
                "XX---\n"
                "X-X--\n"
                "X--X-\n"
                "-----"
            ),
        "s": (
                "----\n"
                "-XXX\n"
                "X---\n"
                "X---\n"
                "-XX-\n"
                "---X\n"
                "---X\n"
                "XXX-\n"
                "----"
            ),
        "t": (
                "---\n"
                "XXX\n"
                "-X-\n"
                "-X-\n"
                "-X-\n"
                "-X-\n"
                "-X-\n"
                "-X-\n"
                "---"
            ),
        "u": (
                "----\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "X--X\n"
                "-XX-\n"
                "----"
            ),
        "v": (
                "-----\n"
                "-----\n"
                "X---X\n"
                "X---X\n"
                "X---X\n"
                "X---X\n"
                "-X-X-\n"
                "--X--\n"
                "-----"
            ),
        "w": (
                "-----\n"
                "X---X\n"
                "X---X\n"
                "X---X\n"
                "X-X-X\n"
                "XXXXX\n"
                "XX-XX\n"
                "X---X\n"
                "-----"
            ),
        "x": (
                "-----\n"
                "X---X\n"
                "X---X\n"
                "-X-X-\n"
                "--X--\n"
                "-X-X-\n"
                "X---X\n"
                "X---X\n"
                "-----"
            ),
        "y": (
                "-----\n"
                "X---X\n"
                "X---X\n"
                "-X-X-\n"
                "--X--\n"
                "--X--\n"
                "--X--\n"
                "--X--\n"
                "-----"
            ),
        "z": (
                "----\n"
                "XXXX\n"
                "--X-\n"
                "--X-\n"
                "-X--\n"
                "-X--\n"
                "X---\n"
                "XXXX\n"
                "----"
            ),
        "|": (
                "-\n"
                "-\n"
                "-\n"
                "-\n"
                "-\n"
                "-\n"
                "-\n"
                "-\n"
                "-"
            ),
        " ": (
                "--\n"
                "--\n"
                "--\n"
                "--\n"
                "--\n"
                "--\n"
                "--\n"
                "--\n"
                "--"
            )
    }